datascience class

In [ ]:
print("welcome to datascience class")

welcome to datascience class


In [ ]:
print("module one")

module one


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [1]:
import pandas as pd
d = {'col1':[2,13,7,15], 'col2':[3,4,5,12], 'col3':[1,8,9,10]}
df = pd.DataFrame(data=d)
print(df)

   col1  col2  col3
0     2     3     1
1    13     4     8
2     7     5     9
3    15    12    10


In [3]:
import numpy as np
myarr=np.array([6,7,8,9,1,2])
print(type(myarr))

<class 'numpy.ndarray'>


In [10]:
import numpy as np
myarr2 = np.array(["lilian", "jane", "james", "john", "peter"])
print(myarr2[2])
print(type(myarr2))

james
<class 'numpy.ndarray'>


In [4]:
from numpy import random
import numpy as np
arr =np.array([1,2,3,4,5])
random.shuffle(arr)
print(arr)

[2 5 4 3 1]


In [11]:
import numpy  as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:6])

[3 4 5 6]
